### ISSUE TITLE
TinyDialogsNet text does not appear properly on macOS

### ISSUE THREAD

**Issue by Ndymario** [shibbo/Fushigi#11]
The message box for if the ROM FS is invalid does not show its message correctly on macOS.
<img width="429" alt="image" src="https://github.com/shibbo/Fushigi/assets/24448227/213ef86c-9f49-4862-87a3-a0e2854c94c8">
(This also very mildly affects the Open Directory dialogue as only the name of the window is messed up)
<img width="1090" alt="image" src="https://github.com/shibbo/Fushigi/assets/24448227/8c706ed7-e32d-473e-848e-954f6cd661a2">

**Comment by shibbo** [comment]
@KillzXGaming please take a peek at this

**Comment by SimplyMerlin** [comment]
Most likely related to https://github.com/nedoxff/TinyDialogsNet/issues/4

**Comment by shibbo** [comment]
closing as we no longer use TinyFileDialogs
