### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by vinnyg0621** [shibbo/Fushigi#114]
**Describe the bug**
it's not letting me open the romFS path

**To Reproduce**
1. Go to RomFS game path
2. Click on the romFS game path I selected
3. it's telling me it doesn't have the model and stage files, but it does have the BancMapUnit

**Expected behavior**
I downloaded a blank level template. but it's still not working

**Screenshots**
![Screenshot 2024-02-17 153629](https://github.com/shibbo/Fushigi/assets/57818441/6c6a642b-a19c-40c8-8361-0c63c0719e17)

**Operating System:**
Windows 11

**Additional context**
I have git and .NET installed too

**Comment by DonavinDraws** [comment]
Your blank template should be in the save directory, the RomFS path is the dump of the base game files. Not a bug.

**Comment by vinnyg0621** [comment]
oh. okay, thank you
