### ISSUE TITLE
Various Course Loading Crashes

### ISSUE THREAD

**Issue by LtSquigs** [shibbo/Fushigi#12]
Platform: OSX

While browsing through the levels I decided to try and load up every course and document what errors or crashes occurred.

Here is a list of all the errors I noticed on course loading:

1. Some Courses do not have a `BgUnits` field defined which causes an exception in [this line](https://github.com/shibbo/Fushigi/blob/main/Fushigi/ui/widgets/CourseScene.cs#L360)
    - Example Course: `World005` - `Course043_Course `
2. Some Courses do not have a `Walls` field defined which causes an exception in [this line](https://github.com/shibbo/Fushigi/blob/main/Fushigi/ui/widgets/CourseScene.cs#L363)
    - Example Course: `World009` - `Course850_Course`
3. Two Courses seem to cause a Hard Crash w/ out any trace back
    - `World009` - `Course859_Course`
    - `World008` - `Course063_Course` - `Course063_Sub1`
4. The Course `Course460_Course` is defined in every world but worlds 8/9. This may be intentional for some reason, but it does cause some weird interactions (such as with the Radio UI, once you select one, all of them are selected)

**Comment by shibbo** [comment]
fixed by feece97
