### ISSUE TITLE
Deleting a rotation controller, then select an object tied to it will crash fushigi

### ISSUE THREAD

**Issue by CasiniLoogi** [shibbo/Fushigi#38]
Basically just delete a rotation controller then select anything tied to it and fushigi will throw a "Object reference not set to an instance of an object", you can find plenty of rotation controllers in 1-1 to test the issue
![image](https://github.com/shibbo/Fushigi/assets/64741221/fe91a6fc-ae33-4e35-81a1-6ddefcf1af18)

**Comment by shibbo** [comment]
fixed with 3688114
