### ISSUE TITLE
Moving a Wall Point and an Actor that intersect moves both at the same time

### ISSUE THREAD

**Issue by break-core** [shibbo/Fushigi#39]
Wall points can be moved around in Fushigi, however an issue occurs when a wall point intersects an actor. If an actor is in the clicking range to a wall point, then what will happen is that both the actor and the wall point will be selected.

The main issue with this is that you cannot undo an actor that was moved when the wall point is moved, it will only move back the point and not the actor as well because Fushigi thinks that only the wall point was selected.

### Example Video
https://github.com/shibbo/Fushigi/assets/71668864/d8fd27b0-726b-458f-9952-4dbd1747c684

### How to Reproduce the Issue
1. Open Fushigi and open any course (I used Course900's main area in the example video)
2. Find a wall point that intersects with an actor
3. Upon moving the wall point, the actor will be moved at the same time.
4. Optionally, you can try undoing and the movement you made to the actor won't be undone. Only the wall point will be undone.

**Comment by shibbo** [comment]
This is due to the editor mode feature not being fully implemented yet. Should be fixed soon
