### ISSUE TITLE
Crash on Save at stage 007

### ISSUE THREAD

**Issue by Emanuele77u** [shibbo/Fushigi#44]
When Saving the level at the stage 007 of world 1 the editor fails and crashes

This is what the console said before crashing:
![image](https://github.com/shibbo/Fushigi/assets/107366573/3d03efe5-be57-47b9-a49b-c32246b3e925)

**Comment by shibbo** [comment]
Looks like this is due to a parameter type not being implemented into the components.

**Comment by shibbo** [comment]
fixed with 72a4d57, be sure to delete `components.json` and let it regenerate.
