### ISSUE TITLE
Deleting actors causes crashing

### ISSUE THREAD

**Issue by iSeeEthan** [shibbo/Fushigi#48]
Whenever you try to delete many actors eventually it crashes and using that level I can't delete any more actors without it crashing.

**To Reproduce**
1. Delete many actors in a row
2. Eventually it will just crash and not let u delete any more

**Expected behavior**
For it too not crash.

**Operating System:**
Win11 x64

**Additional context**
None.

**Comment by shibbo** [comment]
fixed with 5659cd4
