### ISSUE TITLE
Fushigi crash upon selecting any actor from within level with missing actors

### ISSUE THREAD

**Issue by CasiniLoogi** [shibbo/Fushigi#50]
**Describe the bug**
I deleted many elements in 1-1, so I can't determine what specifically is inducing the crash, but the level file attached will cause Fushigi to outright crash when any element is selected. 

**To Reproduce**
1. Download the attached level and load it with Fushigi
2. Select any actors within the main area
3. See error

**Expected behavior**
Fushigi not to crash

**Screenshots**
![Screenshot (42)](https://github.com/shibbo/Fushigi/assets/64741221/e8b94874-e142-4d68-82d4-573b773675ba)

**Operating System:**
 Microsoft Windows 11 Home 10.0.22621 Build 22621

**Attached Files:**
[Crashing Level.zip](https://github.com/shibbo/Fushigi/files/13299351/Crashing.Level.zip)

**Additional Information:**
The level in question will load in-game properly

**Comment by shibbo** [comment]
fixed with 5659cd4
