### ISSUE TITLE
Can't Select negatively scaled objects

### ISSUE THREAD

**Issue by Emanuele77u** [shibbo/Fushigi#53]
If you negatively scale an object you can't select it anymore if you deselect it.

**Comment by shibbo** [comment]
![image](https://github.com/shibbo/Fushigi/assets/22485411/08786aff-cfaf-46e9-a602-28df559276e8)
seems to work for me

**Comment by shibbo** [comment]
negated the issue by disabling scale going below 0 in aa7ce19
