### ISSUE TITLE
Adding a point doesn't work when adding a new wall on a new tile unit

### ISSUE THREAD

**Issue by polskidevv** [shibbo/Fushigi#62]
**Describe the bug**
Adding a point won't work when adding a new wall on a new tile unit

**To Reproduce**
1. Add a new Tile Unit
2. Add a new wall
3. Add new point for said wall

**Expected behavior**
A new point should have been added to the wall in question.

**Comment by KillzXGaming** [comment]
This should be fixed now as of https://github.com/shibbo/Fushigi/commit/ad5b09c87a922db80f1685a79050dd7e17e54111
