### ISSUE TITLE
Editor locks onto the "Area Parameters" box when pressing the up arrow, preventing you from moving the camera up.

### ISSUE THREAD

**Issue by Forwaken** [shibbo/Fushigi#72]
When focused into the viewport tab, if you press or hold the up key, it will mouse you over the "Area Parameters" and stop you from moving the camera upwards.

1. Click on the Viewports tab in Fushigi.
2. Press and hold the Up key
3. Camera moves once and then completely stops.
4. When in this state, you also can't move to the left.

Obviously the intended functionality is for it to just smoothly move the camera upwards when holding the up key.

![image](https://github.com/shibbo/Fushigi/assets/19639498/2043c632-bdcb-48d5-9ee4-0fd7c6de993c)

I use Windows 11.

**Comment by KillzXGaming** [comment]
Fixed https://github.com/shibbo/Fushigi/commit/e692abea09fcf602e7024246e76ee3b20634bd8d
